name : Event Filters and Activity Types

on:
    # pull_request:
    #     types: opened
    #     branches:
    #         - main
    workflow_dispatch:

jobs:
    echo:
        runs-on: ubuntu-latest
        steps:
            - run: echo "This workflow is testing failure"

            - run: exit 1