name: System-Report

on: 
  push:

jobs:
    system-info:
        runs-on: ubuntu-latest
        steps:
            - name: show system information
              run: |
                echo "=== OS ==="
                grep "^PRETTY_NAME /etc/os-release
                echo "=== kernel ==="
                uname -r
                echo "=== Free disk space ==="
                df -h /
                echo "=== Current date and time ==="
                date
            - name: Install tree
              run: |
                sudo apt-get update
                sudo apt-get install -y tree
            - name: show home directory 
              run: |
                tree -L 2 "$HOME"
    tool-check:
        runs-on: ubuntu-latest
        steps:
            - name: Install jq
              run: |
                    sudo apt-get update
                    sudo apt-get install -y jq
            - name: Create report.json
              run: |
                 cat > report.json <<"EOF"
                 {
                   "runner": "ubuntu"
                   "language": "python"
                   "purpost": "system-report"
                 }
                   EOF
            - name: Read json value
              run: |
                jq -r '.runner' report.json
            
            - name: show python version
              run: |
                echo "Python version:"
                python3 --version

                echo "git version:"
                git --version

                echo "jq version:"
                jq --version

            - name: complete report
              run: |
                echo "System report completed successfully."